### PR TITLE
Update for newer Home Assistant versions

### PR DESCRIPTION
**Pull request by iamwillbar**
1. Adopts the updated integration_blueprint template.
2. Creates devices for each light.
3. Migrates from deprecated supported features to color modes.

### CODE REVIEW

**Comment by iamwillbar** [comment]
@sebirdman I just found [https://github.com/DeakoLights/homeassistant_alpha](https://github.com/DeakoLights/homeassistant_alpha/blob/main). Is that the preferred version to use? It looks like it addresses most (all?) of these issues.

**Comment by cdude5464** [comment]
Thank you for maintaining these. I am integrating my Deako lights to HA and wanted to follow up on  @iamwillbar's question regarding the Deako Alpha Integration to see what had been figured out? TIA

**Comment by iamwillbar** [comment]
@cdude5464 I have been using the alpha I linked above successfully, so I'd suggest starting with that. If I find any issues, I plan to submit PR's to that one.

**Comment by iamwillbar** [comment]
I'll close this PR given the alpha working.

**Pull request closed without merging**
