### PR TITLE
Fix control multiple switches at once causes MALFORMED_REQUEST error

### PR DESCRIPTION
**Pull request by caminadab**
Added an async queue to the main controller in the processor/consumer pattern to deal with incoming requests. This causes all incoming requests to change state to have an 800ms delay between calls as specified in the official Deako github to avoid request corruption by the devices.

TODO: make the delay configurable

### CODE REVIEW

**Comment by caminadab** [comment]
Hey @sebirdman, could you please review these changes? :)

**Comment by caminadab** [comment]
I wanted to be able to configure the delay time using a configuration parameter, but thought I would get this reviewed first before I invest more time into it.

**Comment by sebirdman** [comment]
This looks pretty good to me. 

Do you think the time needs to be configurable?

**Comment by caminadab** [comment]
Depends on the direction you want to take this project. 
Having this configurable could be a good setting for someone that only has one or very few light switches. For a lot of light switches, 800ms is pretty much the sweet spot, but you can probably make them a little more responsive with some trial and error.

**Comment by sebirdman** [comment]
Lets merge it for now and then maybe put a separate MR for tweaking it later.

**Pull request merged**
